### ISSUE TITLE
Titles not visible/selectable on a dedicated server until you unlock any titles in single player

### ISSUE THREAD

**Issue by Febilian** [Aurilux/Titles#26] opened 2021-08-09 15:20 UTC
I tested this with nothing but ``Forge 36.2.0`` and ``Titles 3.3.0`` installed both in single player and on a dedicated server. Having done the server test first, I discovered that titles didn't unlock at all in my GUI until I went and unlocked any titles in a single player world too; after that, logging onto the server again actually allowed me to select the advancements that I'd previously unlocked(but didn't show up in the GUI).

In single player, the mod works as expected 100% - advancements and title scrolls acquired from villagers give the player titles they can use from the Titles GUI. But on a dedicated server, titles that should have been unlocked from either advancements or scrolls don't show up in the Titles GUI until you've logged into a single player world with any titles acquired at least once.

I tested this with ``the Spelunker`` and ``the Pincushion`` titles, and by using a Common Title Scroll to acquire those handfuls of titles.

**Comment by Aurilux** [comment] 2021-08-09 15:25
Thank you for posting this. It is a issue I am aware (it is some kind of desync problem), but I am still struggling to locate the cause. I am however currently working on it.

**Comment by OfficialLahusa** [comment] 2021-11-03 19:57
This issue might be related by type to [this issue](https://github.com/Yesssssman/epicfightmod/issues/711), which the mod epic fights currently has

**Comment by Aurilux** [comment] 2022-05-31 02:17
Fixed with 3.3.2

**Closed by Aurilux** 2022-05-31 02:17 UTC
